name: Deploy

on:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  deploy:
    name: "Run deploy scripts"
    runs-on: linux
    steps:
      - uses: actions/checkout@v4
      - name: Sets branch name
        id: extract_branch
        env:
          name: "${{ env.BRANCH_NAME }}"
        run: >
          echo "MODIFIED_BRANCH=$(echo "${name/\//-}" | tr '[:upper:]' '[:lower:]')-tf" >> $GITHUB_OUTPUT
