name: Deploy

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "distinct id"
  # pull_request:
  push:
    branches:
      - "feature/**"

permissions: write-all

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  check_first_push:
    name: "Check if this is first push"
    outputs:
      deploy-all: ${{steps.first-push.outputs.deploy-all}}
    runs-on: ubuntu-latest
    steps: 
      - name: Get commit SHA
        run: echo "SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: "Check if this is first push"
        uses: actions/github-script@v6
        id: first-push
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const sha = '${{ github.ref }}';
            const commitSha = '${{ github.sha }}';

            async function isFirstPush() {
              let runningWorkflows = [];
              const { data: runs } = await github.rest.actions.listWorkflowRuns({
                owner,
                repo,
                workflow_id: 'deploy-branch-environment.yaml',
                branch: '${{ env.BRANCH_NAME }}'
              });

              for (const run of runs.workflow_runs) {
                if (run.id !== run_id) { 
                  runningWorkflows.push(run);
                }
              }
              console.log('Other workflows', runningWorkflows)
              return runningWorkflows.length == 0;
            }
            let foundPrevCommit = false;

            core.setOutput('deploy-all', isFirstPush());
      

  deploy:
    name: "Run deploy scripts"
    runs-on: ubuntu-latest
    needs: [check_first_push]
    if: ${{needs.check_first_push.outputs.deploy-all}}
    steps:
      - uses: actions/checkout@v4

      - name: Get Pull Request Number
        id: pr
        run: echo "pull_request_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sets branch name
        id: extract_branch
        env:
          name: "${{ env.BRANCH_NAME }}"
        run: >
          echo "MODIFIED_BRANCH=$(echo "${name/\//-}" | tr '[:upper:]' '[:lower:]')-tf" >> $GITHUB_OUTPUT
      
      - name: Skip this step
        if: ${{ env.BRANCH_NAME != 'branch'}}
        run: >
          echo "Skipped"
        
      # dispatch test workflow
      # - uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.PAT }}
      #     script: |
      #       await github.rest.actions.createWorkflowDispatch({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           workflow_id: 'test.yaml',
      #           ref: '${{ github.ref }}',
      #           inputs: {
      #             pr_number: '${{ steps.pr.outputs.pull_request_number }}'
      #           },
      #       });
