name: Deploy

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "distinct id"
  # pull_request:
  push:
    branches:
      - "feature/**"

permissions: write-all

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  deploy:
    name: "Run deploy scripts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Pull Request Number
        id: pr
        run: echo "pull_request_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sets branch name
        id: extract_branch
        env:
          name: "${{ env.BRANCH_NAME }}"
        run: >
          echo "MODIFIED_BRANCH=$(echo "${name/\//-}" | tr '[:upper:]' '[:lower:]')-tf" >> $GITHUB_OUTPUT
      
      - name: Skip this step
        if: ${{ env.BRANCH_NAME != 'branch'}}
        run: >
          echo "Skipped"
        
      # dispatch test workflow
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'test.yaml',
                ref: '${{ github.ref }}',
                inputs: {
                  pr_number: ${{ steps.pr.outputs.pull_request_number }}
                },
            });