name: Deploy

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "distinct id"
  pull_request:
  # push:
  #   branches:
  #     - "feature/**"

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  id-token: write
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  deploy:
    name: "Run deploy scripts"
    runs-on: ubuntu-latest
    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}

      - uses: actions/checkout@v4
      - name: Sets branch name
        id: extract_branch
        env:
          name: "${{ env.BRANCH_NAME }}"
        run: >
          echo "MODIFIED_BRANCH=$(echo "${name/\//-}" | tr '[:upper:]' '[:lower:]')-tf" >> $GITHUB_OUTPUT
      - name: Skip this step
        if: ${{ env.BRANCH_NAME != 'branch'}}
        run: >
          echo "Skipped"