name: Run tests

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy"]
    types: 
      - completed
jobs:
  tests:
    name: "Run dummy tests"
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print hello
        run: >
          echo "Hello World!"
      - name: Determine branch name
        run: |
          if ["${{github.event_name}}" == "workflow_run"]; then
            echo "BRANCH_NAME=${{github.event.workflow_run.head_branch}}" >> $GITHUB_ENV
          elif ["${{github.event_name}}" == "workflow_dispatch"]; then
            echo "BRANCH_NAME=${{github.ref_name || github.head_ref}}" >> $GITHUB_ENV
          fi
      - name: Print event branch, hopefully
        run: >
          echo "BRANCH NAME is ${{ env.BRANCH_NAME }}"