name: Run tests

on: 
  workflow_run:
    workflows: ["Deploy"]
    types: 
      - completed
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  tests:
    name: "Run dummy tests"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print hello
        run: >
          echo "Hello World!"
      - name: Print event branch, hopefully
        run: >
          echo ${{ github.event.workflow_run.head_branch}}